---
title: "Generalized Linear Mixed Model on trail running sex-distance-level speed difference"
subtitle: 'Quadratic model'
author: "Franck LE MAT"
date: "03/02/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(data.table)
library(funModeling)
library(pander)
library(scales)
library(lme4)
library(car)
library(fitdistrplus)
library(mgcv)
library(MASS)
library(ggsci)
library(caTools)
library(glmmTMB)
library(Metrics)
library(MuMIn)

######################
## Dataset load 
######################

setwd("~/Project _dataScience/UTMB_dataMining/3. Analysis/")
race_result <- fread('DRV_result.csv')

select_coureur_relatif <- fread('3. MLM_fitting/pair_MLM_4%_unique.csv')

######################
## Variable encoding
######################

df <- inner_join(race_result,
                 select_coureur_relatif,
                 by = c("id_course_annee", "id_coureur"))

df <- df %>%
  filter((id_pair != 639) & (id_pair != 214))

df <- df %>%
  group_by(id_coureur,annee) %>%
  mutate(id_coureur_annee = cur_group_id()) %>%
  ungroup() %>%
  transform(id_coureur_annee = as.factor(id_coureur_annee),
            id_course_annee = as.factor(id_course_annee),
            id_pair = as.factor(id_pair),
            sexe = as.factor(sexe))

class_building <- function(x){
  
  # We select 'short' distance race, meaning race from 25 to 45 km effort
  df_rank <- x %>%
    filter(km_effort >= 25 & km_effort <= 45) %>%
    group_by(id_pair) %>%
    summarise(vitesse_moy_kmE = mean(km_effort)/mean(temps_s/3600), 
              vitesse_moy = mean(vitesse_moy), 
              km_effort = mean(km_effort))
  
  # We create a linear model with those race's speed 
  l_model <- lm(vitesse_moy_kmE ~ km_effort, data = df_rank)
  
  # We adjust the speed in function of the beta coefficient of the linear model
  rank <- df_rank %>% 
    mutate(vitesse_moy_adj = (l_model$coefficients[2]
                              * (km_effort - min(km_effort)))
           + vitesse_moy_kmE)
  
  # We calculate the quartile of the adjuted speed.
  # Each quartile represent a level classification 
  rank <- rank %>%
    mutate(class = cut(x = vitesse_moy_adj, 
                       breaks = quantile(rank$vitesse_moy_adj,
                                         probs = seq(0, 1, 1/4)), 
                       labels = c("Q4", "Q3", "Q2", "Q1"), 
                       include.lowest = TRUE)) %>%
    dplyr::select("id_pair", "class") %>%
    distinct()
  
  x <- x %>%
    inner_join(rank, by = "id_pair")
  return(x)
}

df <- class_building(df)

```

## Model fitting

```{r model fitting}
model1 <- glmmTMB(vitesse_moy ~ poly(km_effort, 1)*sexe*class
                                + (1|id_coureur_annee) 
                                + (1|id_pair) 
                                + (1|id_course_annee),
                  data = df, 
                  family=Gamma(link="log"), 
                  control = glmmTMBControl(parallel = 7))

model2 <- glmmTMB(vitesse_moy ~ poly(km_effort, 2)*sexe*class
                                + (1|id_coureur_annee) 
                                + (1|id_pair) 
                                + (1|id_course_annee),
                  data = df, 
                  family=Gamma(link="log"), 
                  control = glmmTMBControl(parallel = 7))

model3 <- glmmTMB(vitesse_moy ~ poly(km_effort, 3)*sexe*class
                                + (1|id_coureur_annee) 
                                + (1|id_pair) 
                                + (1|id_course_annee),
                  data = df, 
                  family=Gamma(link="log"), 
                  control = glmmTMBControl(parallel = 7))

model4 <- glmmTMB(vitesse_moy ~ poly(km_effort, 4)*sexe*class
                                + (1|id_coureur_annee) 
                                + (1|id_pair) 
                                + (1|id_course_annee),
                  data = df, 
                  family=Gamma(link="log"), 
                  control = glmmTMBControl(parallel = 7))

model5 <- glmmTMB(vitesse_moy ~ poly(km_effort, 5)*sexe*class
                                + (1|id_coureur_annee) 
                                + (1|id_pair) 
                                + (1|id_course_annee),
                  data = df, 
                  family=Gamma(link="log"), 
                  control = glmmTMBControl(parallel = 7))

model1 <- glmmTMB(vitesse_moy ~ poly(km_effort, 2)*sexe + class + class:poly(km_effort, 2)t + sexe:class:poly(km_effort, 2)
                                + (1|id_coureur_annee) 
                                + (1|id_pair) 
                                + (1|id_course_annee),
                  data = df, 
                  family=Gamma(link="log"), 
                  control = glmmTMBControl(parallel = 7))

model1_bis<- glmmTMB(vitesse_moy ~ poly(km_effort, 2)*sexe + class + class:poly(km_effort, 2) + sexe:class
                      + sexe:class:poly(km_effort, 2)
                                + (1|id_coureur_annee) 
                                + (1|id_pair) 
                                + (1|id_course_annee),
                  data = df, 
                  family=Gamma(link="log"), 
                  control = glmmTMBControl(parallel = 7))

anova(model1, model1_bis, type='III')

```

### AIC comparison

```{r random2, echo=FALSE}
aic_value <- AIC(model1,
                 model2,
                 model3,
                 model4,
                 model5)

aic_value$model <- rownames(aic_value)

ggplot(aic_value, aes(x = model,
                      y = AIC)) +
  geom_bar(stat = 'identity',
           fill = 'steelblue') +
  geom_text(aes(label = round(AIC, 2)),
            vjust = -.5)+
  scale_y_continuous(breaks = breaks_pretty()) +
  scale_color_lancet()+
  theme_classic()

```

# Dharma eval

```{r eval2}
library(DHARMa)

model_list <- list(model1, model2, model3, model4, model5)

simulationOutput <- list()

for(model in 1:length(model_list)) {
  simulationOutput[[model]] <- simulateResiduals(fittedModel = model_list[[model]], plot = F)
  
  plot(simulationOutput[[model]])
  summary(model_list[[model]])
}
summary(model2)
```

## Results visualisation 
```{r result viz, fig.width=10, fig.height=14}
library(ggeffects)

model_plot <- list()

for(model in 1:length(model_list)) {
  mydf <- ggpredict(model_list[[model]],
                    terms = c("km_effort [all]", "sexe"))
  
  model_plot[[model]] <- ggplot(mydf,
                               aes(x,
                                   predicted)) +
    geom_line(aes(colour = group)) +
    geom_ribbon(aes(ymin = conf.low,
                    ymax = conf.high,
                    fill = group), 
                alpha = .1,
                show.legend=FALSE) + 
    labs(
      y = "Speed (km/h)",
      x = "km effort (a.u.)",
      colour = "Gender",
      title = paste('km effort polynomial ', model)
    ) +
    scale_x_continuous(breaks = pretty_breaks()) + 
    scale_y_continuous(breaks = pretty_breaks()) +
    scale_fill_lancet() +
    scale_color_lancet() +
    theme_classic()
}

ggpubr::ggarrange(plotlist = model_plot, align = 'hv',
                  ncol = 2,
                  nrow = 3,
                  common.legend = TRUE,
                  labels = "AUTO")

```